### ISSUE TITLE
Create janusgraph configuration entry in ConfigMap

### ISSUE THREAD

**Issue by fridex** [thoth-station/core#142]
**Is your feature request related to a problem? Please describe.**

If we decide to host graph database elsewhere, we should be able to configure it for all the services and pods of thoth at one place. Currently, we hardcoded ``THOTH_JANUSGRAPH_HOST`` and ``THOTH_JANUSGRAPH_HOST`` to each template that is not nice at all.

**Describe the solution you'd like**

We should move it to configmap and ideally make it parametrizable from ansible-playbooks.

**Comment by goern** [comment]
hmm, I think I argued this before... _HOST and _PORT are generic values, they could be derived from the service, no matter if its an internal or external service.

**Comment by fridex** [comment]
So the internal DNS can handle this?

**Comment by fridex** [comment]
Should be derived from service, closing this.
