### ISSUE TITLE
use JanusGraph Service

### ISSUE THREAD

**Issue by goern** [thoth-station/core#153]
**Is your feature request related to a problem? Please describe.**
We want JanusGraph to be exposed as a Service, so that all components could use it via ENV or DNS. At the same time it should be transparent if the service is deployed on the same project or is in external service.

**Describe the solution you'd like**
JanusGraph service in thoth project

**Describe alternatives you've considered**
hard coded use of janusgraph:80 -> to be removed

**Additional context**
n/a

**Comment by fridex** [comment]
I think this can be closed. Thanks for the work!
