### ISSUE TITLE
Create a base image for API services

### ISSUE THREAD

**Issue by fridex** [thoth-station/core#164]
As we are using swagger to document all the endpoints, it could be good to consider creating an own s2i image for API services. The base image would be based on Python3's s2i and would look for swagger.yaml that will act like an entrypoint. The swagger definition (in case of connexion) states where the implementation sits so the base image can directly load swagger.yaml and run the server. All the API server related configuration (setting up logging, setting up listing endpoints, liveness/readiness probes) can be abstracted away to the base image.

**Comment by goern** [comment]
@fridex still valid?

**Comment by fridex** [comment]
> @fridex still valid?

I think it would be "nice to have". I personally like the idea of s2i-api as a base container image as it could simplify creation of API services. However, considering we have just 3 API services, I think this is low priority or we can completely abandon this solution for now.

**Comment by fridex** [comment]
maybe a serverless alternative?
