### ISSUE TITLE
Introduce multiple configmaps respecting semantics

### ISSUE THREAD

**Issue by fridex** [thoth-station/core#167]
As of now we have one large configmap. We should create multiple configmaps respecting their semantics and use ``envFrom`` directive to insert all the configuration options from the given configmap. This way, if we change something for example in logging (e.g. introduce new functionality), we do not need to manually change each and every openshift template.

Candidates are:

* thoth-logging - all the related configuration to logging (rsyslog host/port, sentry, elk host...)
* thoth-ceph - configuration related to ceph (S3 adapter)
* thoth-namespaces - name of namespaces (there is a possibility to introduce new ones in the future)

References:

* https://trello.com/c/KRYZgfKs

**Comment by goern** [comment]
see also https://trello.com/c/KRYZgfKs

**Comment by goern** [comment]
note: changes on configmaps do not trigger redeployments.

**Comment by goern** [comment]
I would get rid of the 'thoth-' prefix as the configmaps live in the same project as the deployments/jobs using it. More complicated: we can not have cross-project configmap/secret references :/

**Comment by fridex** [comment]
> * thoth-namespaces - name of namespaces (there is a possibility to introduce new ones in the future)

One thing here - adviser, package-extract, solver, provenance-checker, ... - these all can have different requests on resources. We use jobs, the k8s scheduler can make some jobs starving as it postpones jobs that have requests larger than the currently available resources in the namespace.

To prevent from this in future/prod deployment, we should make configurable namespaces per analyzer type so we can structure our cluster based on needs, remove possible internal fragmentation (when adjusting resource requests) and so on.

**Comment by fridex** [comment]
> note: changes on configmaps do not trigger redeployments.

In that case we will need to revisit this and adjust trigger all over the places where needed.

**Comment by goern** [comment]
is this still valid with the current state of thoth-ops? @harshad16 @fridex

**Comment by harshad16** [comment]
An interesting issue, so the goal here was to have a setup in which we can modify the config map and relevant deployment is updated. 

> is this still valid with the current state of thoth-ops? @harshad16 @fridex

As of now, we still use one configmap `thoth` .
May be this could be a valid issue, for making thoth of Gen V ;) 
as having trigger to which updates deployments on change of configmaps feels like a good case.

**Comment by goern** [comment]
or it could be the driver to turn Thoth into an ArgoCD application?!
