### ISSUE TITLE
SI Release v0.1.0 BLOCKER

### ISSUE THREAD

**Issue by goern** [thoth-station/core#236]
- [x] https://github.com/thoth-station/workflows/issues/26
- [x] create container images for si-{bandit|cloc|aggragator}
- [x] https://github.com/thoth-station/si-bandit/issues/1
- [x] https://github.com/thoth-station/si-aggregator/issues/1
- [x] https://github.com/thoth-station/graph-sync-job/issues/421
- [x] https://github.com/thoth-station/thoth-application/issues/52
- [x] create argoCD app
- [x] test successfully complete workflow

**Comment by pacospace** [comment]
@harshad16 can you create the SI app when you can in ArgoCD please? so @KPostOffice will test the entire workflow, including syncing part :) Thanks!!

**Comment by pacospace** [comment]
related-to: https://github.com/thoth-station/thoth-application/issues/52

**Comment by harshad16** [comment]
@pacospace  will definitely do that

**Comment by harshad16** [comment]
@pacospace i have setup the argocd application and @KPostOffice ,test out the workflows. :flying_saucer:

**Comment by goern** [comment]
@harshad16 is this done?

**Comment by harshad16** [comment]
@goern , other components are deployed. 
it the tests are successful , then this issue can be closed.

@KPostOffice  can you ack on security indicator running/executing successfully

**Comment by goern** [comment]
ping :)
