### ISSUE TITLE
Update architecture diagram and description with thoth-station updated logics

### ISSUE THREAD

**Issue by harshad16** [thoth-station/core#246]
**Is your feature request related to a problem? Please describe.**
The Thoth-station has been modified with different tools and apps , we would like to track all this update and update them in the documentation.

**Additional context**
https://github.com/thoth-station/core/blob/master/docs/architecture.png

**Comment by fridex** [comment]
Things we should include:

* argo workflows
* kafka
* investigator
* slo reporter


https://thoth-station.ninja/docs/developers/adviser/architecture.html

**Comment by goern** [comment]
And we should figure out a way to describe the different levels: architecture (components coupled via messaging) implementation (Kafka)

**Comment by fridex** [comment]
/close

The docs were updated to give a high-level overview. As we are still in dev mode, let's close this. We can extend docs once the application settles down more as needed.
