### ISSUE TITLE
Show case complete power of Thoth Advise

### ISSUE THREAD

**Issue by harshad16** [thoth-station/core#252]
we would like to showcase Thoth advise feature to advise on AI software stack along with provides necessary change for the deployment of the application on openshift infrastructure. Use AICoE-CI(tekton-pipeline) based application to showcase this feature utilizing the Gitops method. 

The showcase can be done on a sample application on which the aicoe-ci application is installed. 
The ci pipeline would execute a Thoth advise and gather relevant change. 
If the build check passed with the advice stack, the pipeline would update the deployment config with the advised jsonpatch, and create a pull request for the jsonpatch in the gitops repository, along with a pull request for the advice stack to the sample application repository.

**Comment by goern** [comment]
this is the implementation of https://github.com/thoth-station/core/blob/master/docs/ROADMAP.md#reproducible-deployment-pipeline

/kind feature
