### ISSUE TITLE
[spike] thamos integration of rekor

### ISSUE THREAD

**Issue by goern** [thoth-station/core#262]
can we create a "rekor indicator" that will tell the developer that a python module being used in an advice has valid rekor information

As a user of Thoth,
I want to see a "rekor indicator" with my `thamos advise` response,
so that I can understand if the releases that are in my dependencies are authentic

As a Python Index Operator,
I want to run a side car rekor service,
so that developers/publishers can put their module release information in it

As a Python Module Publisher,
I want to publish my module on a Python Index,
and I want to add my release signature to rekor,
so that thamos can use it within an advise

Cc: @lukehinds

**References**

* https://github.com/projectrekor/rekor

**Comment by goern** [comment]
@fridex could you have a little look at this? if feels like Luke might have some nice additional tooling that we can put alongside the SI to have a very strong provenance of dependencies

**Comment by fridex** [comment]
It might be good to refresh the discussion with upstream. Wheel files [can be signed](https://www.python.org/dev/peps/pep-0491/#signed-wheel-files) and `wheel` had the capability of performing such checks. IIRC, pip performs checks respecting [PEP-491](https://www.python.org/dev/peps/pep-0491/#signed-wheel-files) during the installation process. Unfortunately, the support was dropped - see https://github.com/pypa/wheel/issues/196. It might be good to refresh the discussion and see the current position of PyPA to this so we eventually and ideally end up with a standardized solution.

**Comment by fridex** [comment]
There has been already upstream issue which is currently WIP - see [PEP-458](https://www.python.org/dev/peps/pep-0458) and the related PR (https://github.com/pypa/pip/pull/9041) which supports package signing when installing packages from PyPI. I think it might be good to get insights from the community on this topic (https://discuss.python.org/t/rfc-improving-pip-security-with-package-signing-pep-458/5713) - how to manage signed packages outside of PyPI in case of self-hosted package indexes. It looks like the support could land in pip and PyPI.

**Comment by goern** [comment]
@lukehinds the PEP-458 effort seems to be the right place to integrate rekor into the python toolchain. rkor seems to be an alternative to what the python community wants to do right now, so its worth working with them to think about rekor.

**Comment by fridex** [comment]
If there is a plan to integrate rekor into pip/Python, it might be a good idea to get involved in the community efforts. It looks like they are planning to design signing in a specific way. See https://discuss.python.org/t/rfc-improving-pip-security-with-package-signing-pep-458/5713/4
