### ISSUE TITLE
Add support for constraints files

### ISSUE THREAD

**Issue by fridex** [thoth-station/core#271]
**Is your feature request related to a problem? Please describe.**

See discussion in https://github.com/pypa/pipenv/issues/4464

**Describe the solution you'd like**

- [ ] pass content of the `constraints_file` with thamos' reqeuest - https://github.com/thoth-station/thamos/pull/841
- [x] adviser accepts constraints_file and registers appropriate pipeline units to respect constraints - https://github.com/thoth-station/adviser/pull/1826
- [x] constraints are stated in the adviser report - https://github.com/thoth-station/adviser/pull/1826
- [x] user-api accepts and handles constraints (stores them on Ceph) with the request - https://github.com/thoth-station/user-api/pull/1397
- [x] advise workflow handles constraint files - https://github.com/thoth-station/thoth-application/pull/1183
- [x] add relevant justification https://github.com/thoth-station/thoth-station.github.io/pull/206/
- [x] integrate constraints to `Project` abstraction - https://github.com/thoth-station/python/pull/389
- [x] document constraints use - https://github.com/thoth-station/adviser/pull/1839

**Describe alternatives you've considered**

Maintain constraints in Pipfile, which is not recommended.

**Comment by KPostOffice** [comment]
Is this the same issue we had when we had to set `openshift==X.X.Y` in the Pipfile?

**Comment by fridex** [comment]
> Is this the same issue we had when we had to set `openshift==X.X.Y` in the Pipfile?

See [docs](https://pip.pypa.io/en/stable/user_guide/#constraints-files):

> Constraints files are requirements files that only control which version of a requirement is installed, not whether it is installed or not.


An example can be airflow, they pretty nicely described their needs and [constraint files in their docs](https://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files):

> Airflow installation might be sometimes tricky because Airflow is a bit of both a library and application. Libraries usually keep their dependencies open and applications usually pin them, but we should do neither and both at the same time. We decided to keep our dependencies as open as possible (in setup.cfg and setup.py) so users can install different version of libraries if needed. This means that from time to time plain pip install apache-airflow will not work or will produce unusable Airflow installation.
>
> In order to have repeatable installation, starting from Airflow 1.10.10 and updated in Airflow 1.10.13 we also keep a set of "known-to-be-working" constraint files in the constraints-master, constraints-2-0 and constraints-1-10 orphan branches and then we create tag for each released version e.g. constraints-2.0.2. This way, when we keep a tested and working set of dependencies.
> 
> Those "known-to-be-working" constraints are per major/minor Python version. You can use them as constraint files when installing Airflow from PyPI. Note that you have to specify correct Airflow version and Python versions in the URL.

**Comment by fridex** [comment]
This was already done. Closing.

/kind demo
/close
