### ISSUE TITLE
configurable PI proxy

### ISSUE THREAD

**Issue by goern** [thoth-station/core#272]
**Is your feature request related to a problem? Please describe.**
As a Developer or Build Pipeline,
I want to configure a specific host 
so that it is used as a proxy for an PI

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
n/a

**Additional context**
This might be a good feature with companies having their own 'internal PyPI proxy' like nexus or artifactory.

/kind feature
/label triage/needs-information

**Comment by harshad16** [comment]
@goern  can you provide some more information please

**Comment by goern** [comment]
Assuming that an organization is using something like nexus or artifactory, I wonder how we can configure s2i/tekton/thamos to use these as proxies. How does the PyPI name change influence advisor?

**Comment by harshad16** [comment]
https://github.com/thoth-station/thamos#installing-requirements
thamos install -- --proxy socks5h://127.0.0.1:8029 --trusted-host pypi.org
