### ISSUE TITLE
create a Thoth+ODH colloquium

### ISSUE THREAD

**Issue by goern** [thoth-station/core#277]
**Is your feature request related to a problem? Please describe.**
As a person interested in AI and ML,
I want to follow thru a colloquium,
so that I can learn how to do data science on ODH
and so that I can learn how to get advise from Thoth
and so that I can learn how to deploy my application
 
**Describe the solution you'd like**
This is a meta layer on to of the elyra-tutorial, a little bit of operate first etc.
Let's make sure that the current version of ODH is used on op1st for the colloquium.

**Additional context**
This should be an atomic unit that could be done in a day.

**References**
* https://docs.google.com/document/d/1Q1cvVxkEoiZkMAV4UratTEFt0dsyRK6Xn7hfLw8-fn8/edit

Cc: @durandom

/kind feature
/sig docs
/sig user-experience
/priority important-soon
/assign @pacospace

**Comment by durandom** [comment]
cc @isabelizimm

**Comment by isabelizimm** [comment]
> cc @isabelizimm

The media side sounds a bit like the Operate First espresso series (if we were to add an ODH episode). The workshop/code side would be building a more robust version of this workshop (?). If I'm following this correctly.

**Comment by goern** [comment]
@pacospace @isabelizimm @MichaelClifford could you three work on this during the next week? 

see also https://docs.google.com/document/d/1Q1cvVxkEoiZkMAV4UratTEFt0dsyRK6Xn7hfLw8-fn8/edit

**Comment by MichaelClifford** [comment]
@goern +1
