### ISSUE TITLE
provide Ray notebook images

### ISSUE THREAD

**Issue by goern** [thoth-station/core#283]
**Is your feature request related to a problem? Please describe.**
As an ODH user/Data Scientist,
I want to use a Jupyter Notebook Image provided by Thoth
so that I can use Ray packages

**Additional context**
- [ ] make sure Ray is hosted on a PEP503 compliant index
- [ ] add Ray packages to init-job
- [ ] provide integration test to check for Ray guidance by Thoth
- [ ] migrate Erik's repos to thoth-station
- [ ] define notebook images for ODH
- [ ] set up AICoE-CI to build images for ODH
- [ ] tweet about it
- [ ] migrate ray demo to AICoE/

seeAlso https://chat.google.com/room/AAAAKj2lV-I/d9G5ii6Gghk

**Comment by erikerlandson** [comment]
I am generating the latest `ray-ml-notebook` from here:
https://github.com/erikerlandson/ray-ubi/tree/main/images/ray-ml-notebook

I build them all with this:
https://github.com/erikerlandson/ray-ubi/blob/main/build.sh

**Comment by erikerlandson** [comment]
A note on how these images are currently created: I install all the python deps into a `pipenv` environment:
https://github.com/erikerlandson/ray-ubi/blob/main/images/ray-ubi/Dockerfile#L57

This has implications for how I invoke the ray processes in the pods (via `pipenv run` in the install dir):
https://github.com/erikerlandson/ray-odh-demo/blob/main/deploy/odh/ray-cluster-template-cm.yaml#L107

It is not a problem to change the system used to install the python deps, but be aware it may require you to tweak how the ray startup commands are configured in `RayCluster` objects.

**Comment by goern** [comment]
see #311 
/triage accepted
