### ISSUE TITLE
extract source repo from solver document

### ISSUE THREAD

**Issue by goern** [thoth-station/core#286]
**Is your feature request related to a problem? Please describe.**
Let's have some logic to parse out the source repo from a solver document, output just one URL to stdout. The function could be prototyped in a jupyter notebook

related: https://github.com/thoth-station/thamos/issues/868

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
this is a generally handy method.

/kind feature
/triage needs-information
/assign @pacospace 
/assign @bjoernh2000

**Comment by goern** [comment]
seeAlso https://github.com/thoth-station/datasets/tree/master/notebooks/thoth-solver-dataset

**Comment by pacospace** [comment]
isn't it part of python package metadata synced into the database (e.g. `home page`)? cc @fridex

**Comment by fridex** [comment]
> isn't it part of python package metadata synced into the database (e.g. `home page`)? cc @fridex

We need a mechanism that detects URL to the GitHub repo. Besides `url`, `download_url` you can state also `project_urls` in the `setup.py` - see [docs](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls). The algorithm that would extract repo from the solver repo has to consider all of these as it is up to project maintainer how these URLs are structured in setup.py.

**Comment by goern** [comment]
@bjoernh2000 I think you are working on this, right?

/priority important-soon
/lifecycle active

**Comment by bjoernh2000** [comment]
> @bjoernh2000 I think you are working on this, right?
> 
> /priority important-soon
> /lifecycle active

Yes in progress of adding some changes
