### ISSUE TITLE
[BYON] End to end integration of custom notebook CI/CD to ODH@op1st.cloud

### ISSUE THREAD

**Issue by goern** [thoth-station/core#308]
Bring-your-own-Notebook: End to end integration of custom notebook CI/CD automation integrated in ODH and validated with 3 different use case examples / tutorials / demos.

**Is your feature request related to a problem? Please describe.**
demo an End to end integration of custom notebook CI/CD automation. Notebook should be built and delivered to quay, used in an ODH deployment. Validated with 3 different use case notebooks/examples/tutorials.

**High-level Goals**
Create tutorial/demo repos and deployment similar to Elyra tutorial.

**Describe the solution you'd like**
tbd

**Describe alternatives you've considered**
n/a

**Additional context**
This is a key result we want to achieve in 21Q3

**Acceptance Criteria**
- [x] manage-dependencies-tutorial can be run on Operate First
- [ ] overlays-for-ai-pipeline-tutorial can be run on Operate First
- [ ] recommend-base-image-tutorial can be run on Operate First

**Comment by pacospace** [comment]
Tutorials: 

- [ ] manage-dependencies-tutorial
- [ ] recommend-base-image-tutorial
- [ ] overlays-for-ai-pipeline-tutorial
- [ ] receive-feedback-on-deployment-tutorial

Source: https://docs.google.com/document/d/14a87wrf17C4kfsBsW5SyhLI07sSEAji1Ep6ewxk57K0/edit#

**Comment by pacospace** [comment]
Pre-requisites: https://github.com/AICoE/aicoe-ci/issues/137
Pre-requisites: https://github.com/thoth-station/jupyterlab-requirements/issues/345
Pre-requisites: https://github.com/AICoE/aicoe-ci/issues/136

**Comment by pacospace** [comment]
currently blocked by: https://github.com/operate-first/SRE/issues/382, I need kfp for two of the tutorials!

**Comment by pacospace** [comment]
Still blocked by https://github.com/operate-first/support/issues/435

**Comment by codificat** [comment]
/remove-lifecycle active
as development on the tutorials is currently blocked
