### ISSUE TITLE
Predictable Stack Pattern: Pattern defined and implemented for 3 different stacks.

### ISSUE THREAD

**Issue by goern** [thoth-station/core#309]
**High-level Goals**
We want to show how to declare a predictable stack, and how it is automatically maintained using Thoth Guidance Services. We want to give a demo of the predictable stack pattern.

**Describe the solution you'd like**
tbd

**Acceptance Criteria**

- [x] 3 repositories on github.com hosting a predictable stack declaration
- [x] AICoE-CI based pipeline delivering container images for ODH
- [x] Kebechet maintaining dependencies for each repository (overlay)
- [x] Kebechet uses `thoth_advise` manager to maintain dependencies

**Comment by pacospace** [comment]
- [ ] create a sequence diagram

**Comment by goern** [comment]
@harshad16 could you try to wrap this up the next week? It looks like all the parts are in place. A short writeup how we deliver the PS to ODH could deliver this key result.

**Comment by codificat** [comment]
/triage accepted
as this is mostly complete.

Only pending is some additional documentation.
