### ISSUE TITLE
Ray images available through Thoth guidance.

### ISSUE THREAD

**Issue by goern** [thoth-station/core#311]
**High-level Goals**
Provide Ray images to ODH community, build using through Thoth guidance via AICoE-CI, delivered to quay

**Describe the solution you'd like**
tbd

**Describe alternatives you've considered**
n/a

**Additional context**
This is a key result we want to achieve in 21Q4

**Acceptance Criteria**

- [x] (proposed) s2i-ray-thoth is available on ODH/Operate First

**Supporters**
@harshad16 
@pacospace

**Comment by erikerlandson** [comment]
I am starting to populate the new ray image build repos under thoth-station

**Comment by erikerlandson** [comment]
currently blocked by https://github.com/AICoE/aicoe-ci/issues/130

**Comment by goern** [comment]
@erikerlandson any update on this?!

**Comment by erikerlandson** [comment]
@goern   https://github.com/AICoE/aicoe-ci/issues/130

**Comment by harshad16** [comment]
These would be the repos that would contain the ray content:
https://github.com/thoth-station/ray-operator
https://github.com/thoth-station/ray-ml-worker
https://github.com/thoth-station/ray-ml-notebook


All the images are built through them:
- https://quay.io/repository/thoth-station/ray-ml-worker?tab=tags
- https://quay.io/repository/thoth-station/ray-operator?tab=tags
- https://quay.io/repository/thoth-station/s2i-ray-ml-notebook?tab=tags

closing this issue as all content is available now.
