### ISSUE TITLE
create a pipeline to fullfill "what Thoth knows about your project" teaser feature

### ISSUE THREAD

**Issue by goern** [thoth-station/core#314]
**Is your feature request related to a problem? Please describe.**
in support of https://github.com/AICoE/meteor/issues/92 we deploy a service that will take a user repos, and create a PR containing a Thoth Advise. This is basically what Kebechet's thoth-advise manager does, but invoked in a different way.

**High-level Goals**
A microservice and an Argo Workflow to implement this. SLO Metrics and a dashboard.

**Describe the solution you'd like**
tbd

**Describe alternatives you've considered**
tbd

**Additional context**
This is an addition to the meteor UI that we could use as an ad during DevConf.US

**Acceptance Criteria**
- [ ] document concept for already forked repos
- [ ] implement service for initial fork/submission of a repo
- [ ] define the interface between Thoth microservice and AICoE Meteor
- [x] https://github.com/thoth-station/thoth-application/issues/1893
- [ ] metrics about 'number of invocations of microservice (checked boxes)', 'created PR', 'accepted PR' is provided to be scraped
- [ ] metrics are scraped by Prometheus and visualized by Grafana

**Comment by goern** [comment]
@harshad16 @KPostOffice maybe the artifact/service we deliver here is not a restful microservice, but a Tekton pipeline?!

**Comment by codificat** [comment]
> Rotten issues close after 30d of inactivity.

this was not rotten back then - bot bug, fixed now
/reopen
/remove-lifecycle rotten

**Comment by goern** [comment]
what is the status of this?

**Comment by goern** [comment]
any updates on this? do we consider it done?

**Comment by KPostOffice** [comment]
@goern
@tumido We have an endpoint in user-api for running this type of request. How hard would it be to add this to meteor?

**Comment by goern** [comment]
@tumido ping

**Comment by codificat** [comment]
Reviewing if this was a legitimate closure or if this had to be reopened.

I believe that the functionality requested here is currently tracked in https://github.com/AICoE/meteor-operator/issues/43

Leaving this one as closed then.
