### ISSUE TITLE
document how to create a new repo in thoth station

### ISSUE THREAD

**Issue by pacospace** [thoth-station/core#319]
**Is your feature request related to a problem? Please describe.**
As Thoth Contributor,

I would like to have a document on how to get new repo and configure it.  

**High-level Goals**
Have a document on how to get new repo and configure it.

**Describe the solution you'd like**
Document on how to get new repo and configure it.

**Describe alternatives you've considered**

**Additional context**

**Acceptance Criteria**
- [ ] document steps on how to create a new repo, what is the mechanism and components involved behind it.
- [ ] document the estimated time to receive one new repo.
- [ ] document how to set privileges for members on that repo and all configurations possible. 
- [ ] document how to enable tide.
- [ ] document how to enable prow.
- [ ] document also about CODEOWNERS, OWNERS behaviour (maybe also respect to .aicoe.yaml)

**Comment by goern** [comment]
@tumido @quaid have you guys done this for op1st, so that we can borrow it?

**Comment by quaid** [comment]
> @tumido @quaid have you guys done this for op1st, so that we can borrow it?

Is this what you need?

https://github.com/operate-first/community-handbook/blob/main/content/how-to-request-a-repository.md


That's the Operate First Community Handbook, the new, growing go-to location for everything a contributor needs.

**Comment by goern** [comment]
@quaid cool thanks, but we are actually looking for the opposite side of the issue: how to implement it (creating the repo on GitHub), 

An issue opened based on https://github.com/operate-first/community-handbook/blob/main/content/how-to-request-a-repository.md would be "answered" with something similar to https://github.com/thoth-station/core/pull/320 which would close the issue on merge. 

Why does this work, because bots: https://github.com/thoth-station/core/blob/master/.prow.yaml#L14

**Comment by pacospace** [comment]
@harshad16 pointed me to https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos, we can mention what to open in the PR and described a bit more what is happening, wdyt @goern ?

**Comment by pacospace** [comment]
> @harshad16 pointed me to https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos, we can mention what to open in the PR and describe a bit more what is happening, wdyt @goern ?

Moreover point to some specific things, dependending on the use case: https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization

**Comment by pacospace** [comment]
Remember to add repos under SrcOps for the bots: https://github.com/AICoE/common/pull/23#discussion_r702728025

**Comment by pacospace** [comment]
Document also how to enable prow on repos, see https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/smaug/config.yaml#L248

**Comment by goern** [comment]
The issue comment point to the right pieces, they just need to be written up!

@tumido @quaid can any of the op1st ppl do it?

**Comment by goern** [comment]
https://github.com/thoth-station/thoth-application/issues/1992
