### ISSUE TITLE
[5pt] Make sure ps-stacks can receive recommendation from Thoth

### ISSUE THREAD

**Issue by pacospace** [thoth-station/core#326]
**Describe the bug**
As User of Thoth PS images,

I want to have continous updates on software stacks to be maintained by Thoth services.

**To Reproduce**
1. Run thamos advise on all ps-stacks

**Expected behavior**
All ps-* stacks can be advised by Thoth (all integration tests are green for ps-stacks: https://github.com/thoth-station/integration-tests/issues/204)

**Screenshots**

**Additional context**
ps-*: 

- https://github.com/thoth-station/ps-nlp
- https://github.com/thoth-station/ps-cv

**Comment by goern** [comment]
any update on this?

**Comment by codificat** [comment]
In the last integration test runs there are errors in some of the ps-* tests: ps-cv-{pytorch,tensorflow} and ps-nlp-tensorflow.

They failed due to tmieouts:

```
2022-05-02 03:41:12,899 thoth.adviser.run           ERROR: Child exited with exit code 10
```

Other related integration tests succeeded.

**Comment by codificat** [comment]
/remove-sig user-experience
/sig stack-guidance

because there are issues resolving the stacks here

**Comment by fridex** [comment]
Tested with `stable` recommendation type:

- ps-nlp-tensorflow succeeded - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503173442-64a56b00a848225b)
- ps-nlp-pytorch failed - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503173542-1fa6eba4fc395949)
- ps-cv-tensorflow failed - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503173605-c9d325f97f7a964e)

**Comment by fridex** [comment]
Tested with `latest` recommendation type without jupyterlab-tensorboard package in the stack:

* ps-nlp-tensorflow succeeded  - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503181733-465a91511d855f45)
* ps-nlp-pytorch suceeded - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503181542-e57de5e790f49d5a)
* ps-cv-tensorflow succeeded - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503181236-ef919c9a11ada917)

**Comment by fridex** [comment]
Tested with `latest` recommendation type and `jupyter-tensorboard==0.1.1` (solvable using our solver):

* ps-nlp-tensorflow succeeded - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503182315-80ca048fff9d5395)
* ps-nlp-pytorch succeeded - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503182357-293e0094bf9bf1da)
* ps-cv-tensorflow succeeded - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503182737-21f5a93e8eafdf4a)

**Comment by harshad16** [comment]
> Basically, jupyter-tensorboard expects jupyterlab to be already installed during the installation process (it registers itself). Our solver has no jupyterlab installed when it tries to install jupyter-tensorboard so it fails to obtain dependency information (it was observed for some versions). This behaviour is not very nice, but Python packaging supports it. This can support the first paragraph stated as adviser might be failing to find suitable versions when latest recommendation type is used.

This means our solvers are not able to solve jupyter-tensorboard or other packages with such requirements, right?
Is that the reason we are pinning the jupyter-tensorboard to 0.1.1, or we are pinning it because thoth advice suggested it?

**Comment by fridex** [comment]
> > Basically, jupyter-tensorboard expects jupyterlab to be already installed during the installation process (it registers itself). Our solver has no jupyterlab installed when it tries to install jupyter-tensorboard so it fails to obtain dependency information (it was observed for some versions). This behaviour is not very nice, but Python packaging supports it. This can support the first paragraph stated as adviser might be failing to find suitable versions when latest recommendation type is used.
> 
> This means our solvers are not able to solve jupyter-tensorboard or other packages with such requirements, right?

Generally, no - we are not able to solve libraries that have hard requirements on environment that are not met in our solvers. Ideally, jupyter-tensorboard should not depend on the environment and execute code during the installation process - at least not make it a hard requirement (if it fails, the installed package can still be present). 

This might get better over time as python packaging evolves (and provides static wheel metadata).

> Is that the reason we are pinning the jupyter-tensorboard to 0.1.1, or we are pinning it because thoth advice suggested it?

There can be found versions that were removed in the stack info provided to the user:

```
"The following versions of 'jupyter-tensorboard' from 'https://pypi.org/simple' were removed due to installation issues in the target environment: 0.2.0, 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.4.dev0, 0.1.3, 0.1.3.dev0, 0.1.2, 0.1.2.dev1, 0.1.2.dev0"
```

Thoth also suggested to use it, for example in the first successful resolution with `stable` recommendation type:

> - ps-nlp-tensorflow succeeded - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503173442-64a56b00a848225b)

**Comment by fridex** [comment]
> Thoth also suggested to use it, for example in the first successful resolution with `stable` recommendation type:
> 
> > * ps-nlp-tensorflow succeeded - [see results](https://khemenu.thoth-station.ninja/api/v1/advise/python/adviser-220503173442-64a56b00a848225b)

And for others, it looks like it failed as it did not find any resolution in the allocated time.

**Comment by harshad16** [comment]
ack, thanks for the explanation.

**Comment by codificat** [comment]
The integration tests in stage are suffering from cluster issues that have been going on for a while and are expected to take some more time to fix.

Meanwhile, though, a current test of all the overlays using the production environment provided successful advice:

| overlay               | type   | result  | advise ID                               | time   |
|-----------------------|--------|---------|-----------------------------------------|--------|
| ps-nlp-pytorch        | latest | success | adviser-220613115118-b406e285a0ae8618| 2m 2s  |
| ps-nlp                | latest | success | adviser-220613143911-3483a20bdb243903 | 49s    |
| ps-nlp-tensorflow     | latest | success | adviser-220613144121-b52e7ffa560ce6c6 | 1m 47s |
| ps-nlp-tensorflow-gpu | latest | success | adviser-220613144345-97b1d4046d403a80 | 2m 4s  |

**Comment by codificat** [comment]
> Meanwhile, though, a current test of all the overlays using the production environment provided successful advice with the `latest` recommendation type (what is currently configured in `.thoth.yaml`).

Based on this, I believe we can
/close
this one as complete.

We still need to ensure that integration tests, that include checks for successful advices on the predictable stacks, run successfully (e.g. https://github.com/thoth-station/integration-tests/issues/324), and possibly review the justification related to the failures on some combination of stack/type. 

These are tracked in separate issues as appropriate.
