### ISSUE TITLE
Local development integration with toolbox for Python 3.9 and RHEL9

### ISSUE THREAD

**Issue by goern** [thoth-station/core#341]
A suggested edit of this issue's description that expands it and incorporates #342:

# Local development integration with toolbox for Python 3.9 and RHEL9

Based on the Jupyter Notebook images we provide, we want to provide [toolbox](https://github.com/containers/toolbox) enabled images that can be used to run a jupyter notebook on a local laptop.

This is a migration step during bringing your own notebooks to [OpenDataHub](https://opendatahub.io/) (ODH).

## High-level Goals

Create a Kebechet-maintained toolbox container image that could be used in a local development environment as an extension/a base for all Thoth ODH images.

The image would contribute to a more gentle and complete developer workflow by allowing a developer to:

- kickstart local development quickly and without effort: just use the toolbox image to work on your code/notebooks without having to install devel stacks and worry about dependencies
- the resulting local dev environment provides Thoth's features out of the box
- easily transition to and from hosted and local development environments: the same tools and features are available locally and remotely

## Describe the solution you'd like

As a pre-requisite, as the upcoming RHEL9 will use Python 3.9, we need to prepare our toolchain for this:

- [s2i-thoth](https://github.com/thoth-station/s2i-thoth) and [thoth-ops-infra](https://github.com/thoth-station/thoth-ops-infra) need to be updated
- pytest and mypy toolchain needs to be provided for py39
- advises are available for the 3.9 stack

With that in place, the toolbox images should aim at minimal drift.

The top priority is user experience, but the guiding principle is to use/mimic the hosted/online counterparts' content and workflow as much as possible.

## Additional context

This is a Key Result we want to deliver in the first half of 2022.

## Acceptance Criteria

- [ ] all the Thoth toolchain works with Python 3.9 and RHEL9
- [ ] toolbox container images are provided on quay.io
- [ ] published sample notebooks/applications are verified to work with the tools in a local laptop
  - [ ] automated testing ensures that these continue to work
- [ ] a demo is recorded and published
- [ ] a tutorial is published for developers to get started

## See also

- #308
- https://chat.google.com/room/AAAAVjnVXFk/Fu3w7uwPjW8

**Comment by codificat** [comment]
A suggested edit of this issue's description that expands it and incorporates #342:

# Local development integration with toolbox for Python 3.9 and RHEL9

Based on the Jupyter Notebook images we provide, we want to provide [toolbox](https://github.com/containers/toolbox) enabled images that can be used to run a jupyter notebook on a local laptop.

This is a migration step during bringing your own notebooks to [OpenDataHub](https://opendatahub.io/) (ODH).

## High-level Goals

Create a Kebechet-maintained toolbox container image that could be used in a local development environment as an extension/a base for all Thoth ODH images.

The image would contribute to a more gentle and complete developer workflow by allowing a developer to:

- kickstart local development quickly and without effort: just use the toolbox iimage to work on your code/notebooks without having to install devel stacks and worry about dependencies

- the resulting local dev environment provides Thoth's features out of the box
  
- easyly transition to and from hosted and local development environments: the same tools and features are available locally and remotely

## Describe the solution you'd like

As a pre-requisite, as the upcoming RHEL9 will use Python 3.9, we need to prepare our toolchain for this:

- [s2i-thoth](https://github.com/thoth-station/s2i-thoth) and [thoth-ops-infra](https://github.com/thoth-station/thoth-ops-infra) need to be updated.

- pytest and mypy toolchain needs to be provided for py39

- advises are available for the 3.9 stack

With that in place, the toolbox images should aim at minimal drift.

The top priority is user experience, but the guiding principle is to use/mimic the hosted/online counterparts' content and workflow as much as possible.

## Additional context

This is a Key Result we want to deliver in the first half of 2022.

## Acceptance Criteria

- [ ] all the Thoth toolchain works with Python 3.9 and RHEL9

- [ ] toolbox container images are provided on quay.io

- [ ] published sample notebooks/applications are verified to work with the tools in a local laptop

  - [ ] automated testing ensures that these continue to work

- [ ] a demo is recorded and pubished

- [ ] a tutorial is published for developers to get started


## See also

- #308

- https://chat.google.com/room/AAAAVjnVXFk/Fu3w7uwPjW8

**Comment by goern** [comment]
@fridex @codificat shall we push this back to the backlog?
