### ISSUE TITLE
Explain Thoth as a server-side dependency resolver

### ISSUE THREAD

**Issue by codificat** [thoth-station/core#350]
**Is your feature request related to a problem? Please describe.**

As a Python developer I would like to understand the benefits that Thoth brings to my Python development workflow as a dependency resolution engine, so that I can better consider the pros and cons of Thoth-powered server-side resolution of package dependencies when compared to the current local resolvers.

**High-level Goals**

Showcase Thoth with the specific focus of the package resolution process for a Python developer.

**Describe the solution you'd like**

A set of materials (video demo, blog post, tutorial, documentation) that highlights Thoth in the context of a server-side approach to package resolution.

**Describe alternatives you've considered**

The (default) alternative are local resolvers. A comparison with these alternatives should be part of the resolution of this issue.

**Additional context**

During the [packagingCon conference](https://packaging-con.org) there was a discussion in the chat around the Python dependency resolution process. Thoth was mentioned during that discussion, with a reference to https://discuss.python.org/t/8883. The Thoth team then talked about this in the team chat https://chat.google.com/room/AAAAVjnVXFk/xjm52EGFZcc

There are already existing relevant resources, including:

- https://dev.to/fridex/how-to-beat-python-s-pip-solving-python-dependencies-2d6e
- https://dev.to/fridex/how-to-beat-python-s-pip-inspecting-the-quality-of-machine-learning-software-1pkp

**Acceptance Criteria**

- [ ] an article about Thoth's resolver vs local resolvers
  - [ ] the article includes (or clearly points to) easy to try steps to help people see by themselves
- [ ] a short accompanying video / mini-demo

**Comment by goern** [comment]
any updates on this? do we consider it done?

**Comment by mayaCostantini** [comment]
If we look at acceptance criteria:

- [ ] an article about Thoth's resolver vs local resolvers
  - [x] the article includes (or clearly points to) easy to try steps to help people see by themselves
- [x] a short accompanying video / mini-demo

I think the only missing aspect is the Thoth vs. local resolvers comparison which should be detailed by the overarching article we are writing with Frido for next.redhat.com

The Managing Vulnerabilities with Thoth Tutorial, the corresponding article and the Czech talk video + demo should cover the last two points.

**Comment by mayaCostantini** [comment]
Closing this issue as the [article](https://www.redhat.com/architect/manage-python-dependencies-thoth) was published on Red Hat Enable Architect.
