### ISSUE TITLE
Endpoint for triggering initialization of a repository by Thoth

### ISSUE THREAD

**Issue by fridex** [thoth-station/core#371]
## Problem statement

As a user of Thoth, or as an integration for Thoth services, I would like to trigger a workflow on Thoth's backend that verifies content of my repository and makes sure it is in a healthy state.

- [ ] https://github.com/thoth-station/user-api/pull/1526
- [ ] ...

**Comment by fridex** [comment]
I think this feature is related to the work you do. It is related to the meteor integration feature. The issue was created to better track who works on what.

If you don't see it relevant, feel free to close it or adjust the description. It could help with work tracking.

**Comment by KPostOffice** [comment]
Ahh got it. That's what I got from the title but I wasn't sure about the "verifies content of my repository and makes sure it is in a healthy state". I will close this as I think it is tracked elsewhere.
