### ISSUE TITLE
OCTO Summit Demo

### ISSUE THREAD

**Issue by goern** [thoth-station/core#377]
OCTO summit Demo is showcasing an end-to-end demonstration of various tools, components, and services from the realm of OCTO. As a part of this, Thoth tools and aicoe ci/cd is included.  we have to ensure catering to the needs of the demo. 

**Acceptance criteria**

- [x] CI/CD tool can build and deliver image artifacts for deployment.
  - [x]  Allow multi-build service via CI.
  - [x]  Support multi-arch build service via CI.
  - [x]  Custom deliver to openshift job

- [ ] Recommendation from project Thoth on the demo app.
  - [ ] Advice based on arm architecture apart from traditional x86.
  - [ ]  Details on the recommendation.

**Additional Context**

Related Issues: 
- https://github.com/AICoE/summit-2021-octo-keynote/issues/63
- https://github.com/AICoE/summit-2021-octo-keynote/issues/57

/assign @harshad16

**Comment by harshad16** [comment]
All the pieces in summit demo are already supported
closing this issue.
