### ISSUE TITLE
Introduce jupyterlab collaborative

### ISSUE THREAD

**Issue by pacospace** [thoth-station/core#383]
**Is your feature request related to a problem? Please describe.**
Introduce jupyterlab collaborative: https://jupyterlab.readthedocs.io/en/latest/user/rtc.html

**Describe the solution you'd like**
- [ ] Verify with SIG DS if the team is interested
- [ ] Implement https://github.com/thoth-station/s2i-minimal-notebook/pull/80/files

**Describe alternatives you've considered**

**Additional context**

**Comment by codificat** [comment]
/priority backlog

And I believe that until we confirm interest from SIG-DataScience and/or others (opendatahub maybe?):
/triage needs-information
