### ISSUE TITLE
Create GitHub action that integrates with Thoth

### ISSUE THREAD

**Issue by fridex** [thoth-station/core#397]
## Problem statement

As a user of GitHub, I would like to use a GitHub action on my repository that integrates with Thoth. The GitHub action can use Thamos CLI to contact Thoth backend to get results. For example, if there is a security vulnerability, the GitHub action can turn pull-request to red state, eventually blocking merge.

This feature is an addition to Kebechet for teams that would like to consume Thoth recommendations but do not want to install kebechet on their own. The GitHub action could be designed in a way so that users do not need to keep configuration in their repositories at all (ex. detect where requirements are stated and such).

**Comment by fridex** [comment]
A tutorial: https://lab.github.com/githubtraining/github-actions:-hello-world

**Comment by fridex** [comment]
I think we had an issue like this opened by someone outside of the team, but I cannot find it. Feel free to close this one as a duplicate if you find it.

**Comment by codificat** [comment]
> I think we had an issue like this opened by someone outside of the team, but I cannot find it.

That would be https://github.com/thoth-station/support/issues/193 I believe.

However, this issue description contains suggestions that are not part of the acceptance criteria in the other, e.g. the usage as a CI check.

> Feel free to close this one as a duplicate if you find it.

I was about to mark it as duplicate and close, but the other would have to be expanded a bit to cover the ideas here I believe. Maybe they are complementary?

**Comment by mayaCostantini** [comment]
The test repository for this GitHub action is available at [thoth-github-action-test](https://github.com/mayaCostantini/thoth-github-action-test). For the moment, this first iteration only supports the `Pipfile` format for requirements but I will add support for other formats such as `setup.cfg` soon.
Any improvement proposal is welcome :+1:

**Comment by mayaCostantini** [comment]
The Thoth github action is now available at https://github.com/marketplace/actions/thoth-adviser
Closing this issue.
