### ISSUE TITLE
review BuildConfig, ImageStreams, CronJobs to use same nameing scheme

### ISSUE THREAD

**Issue by goern** [thoth-station/core#41]
Some CronJobs and their ImageStreams and BuildConfig use different naming schemata for the Images.

> **fridolin** btw we should design naming in cronjobs - sometimes there are -cronjobs sometimes -jobs suffixes
> **goern** ja, I know  stumbled about that a few times last week I guess the image should be -job as we can run it manually or via cronjob the BC should be -job, the CronJob without any postfix

**Comment by fridex** [comment]
Fixed in https://github.com/thoth-station/core/pull/43 and in commits in *-job repos.
