### ISSUE TITLE
Projects not enabled even though the configuration is set up

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/core#419]
## Bug description
Related to https://github.com/thoth-station/core/pull/418
and https://github.com/thoth-station/mi/issues/589

### Steps to Reproduce
```
>>> GITHUB_ACCESS_TOKEN=<token>

>>> from github import Consts
>>> from github import Github
>>> gh = Github(login_or_token=GITHUB_ACCESS_TOKEN)
>>> src = gh.get_repo("thoth-station/srcops-testing")

>>> issue = src.get_issue(266)

>>> timeline = github.PaginatedList.PaginatedList(
            github.TimelineEvent.TimelineEvent,
            issue._requester,
            f"{issue.url}/timeline",
            None,
            headers={"Accept": "application/vnd.github.starfox-preview+json,application/vnd.github.mockingbird-preview"},
        )

>>> timeline.totalCount
0
```

### Actual behavior
totalCount of the timeline should be greater than 0, and at least of 3 (because I've added the testing issue into three multiple projects)
That means project related timeline events are still not available.

On top of that, if I go to the settings of `srcops-testing`, it still says following
![image](https://user-images.githubusercontent.com/46632404/176895321-e1ba8c0f-e6b5-45c7-b012-485c7cbe20af.png)
implying that perhaps other setting needs to be updated, generally for all `thoth-station/*` repos

### Expected behavior
Project related events should appear when retrieving timeline for issue that is assigned to a project.

**Comment by xtuchyna** [comment]
@harshad16

**Comment by harshad16** [comment]
@xtuchyna  seems like we have to make this option https://github.com/thoth-station/core/blob/a6bd40e5cb89fa4a2475cd896f625a52f12f5c78/community/github-config.yaml#L17 `true` 
to get everything working in right order.

**Comment by codificat** [comment]
/assign @xtuchyna 
Dominik, is this still an issue?

**Comment by goern** [comment]
/close
feel free to re-open
