### ISSUE TITLE
Review the repos in org and update owners

### ISSUE THREAD

**Issue by harshad16** [thoth-station/core#423]
## Problem statement
Pull request in orgs are not getting appropriate attention as the owners and reviewer are not optimal. we should update the list and work on getting better reviewers.

## Acceptance Criteria

- [ ] example

**Comment by goern** [comment]
please keep alumni approvers as such in the OWNERs file

/priority important-soon
/triage accepted
/kind cleanup
/sig devsecops

**Comment by VannTen** [comment]
Do we have specific repos we're concerned about ?

Maybe the owner should not list specific people, but alias to SIGs members ? That would avoid duplication certainly.

/triage needs-information

**Comment by harshad16** [comment]
Not specific repos, 
generally most of the repo.

sig-members seems to be a good way to go.
though we have started to update this with current members active on the repo.

**Comment by harshad16** [comment]
Some repos are already adjusted:
https://github.com/thoth-station/solver/blob/master/OWNERS
https://github.com/thoth-station/python/blob/master/OWNERS
https://github.com/thoth-station/package-update-job/blob/master/OWNERS
https://github.com/thoth-station/integration-tests/blob/master/OWNERS
https://github.com/thoth-station/thamos/blob/master/OWNERS
https://github.com/thoth-station/document-sync-job/blob/master/OWNERS
https://github.com/thoth-station/prescriptions/blob/master/OWNERS
https://github.com/thoth-station/management-api/blob/master/OWNERS
https://github.com/thoth-station/storages/blob/master/OWNERS
https://github.com/thoth-station/invectio/blob/master/OWNERS
https://github.com/thoth-station/user-api/blob/master/OWNERS
https://github.com/thoth-station/workflow-helpers/blob/master/OWNERS
https://github.com/thoth-station/investigator/blob/master/OWNERS
https://github.com/thoth-station/graph-refresh-job/blob/master/OWNERS
https://github.com/thoth-station/prescriptions-refresh-job/blob/master/OWNERS
https://github.com/thoth-station/cve-update-job/blob/master/OWNERS
https://github.com/thoth-station/graph-backup-job/blob/master/OWNERS
https://github.com/thoth-station/package-releases-job/blob/master/OWNERS
https://github.com/thoth-station/metrics-exporter/blob/master/OWNERS
https://github.com/thoth-station/common/blob/master/OWNERS
https://github.com/thoth-station/package-extract/blob/master/OWNERS
https://github.com/thoth-station/graph-sync-job/blob/master/OWNERS
https://github.com/thoth-station/slo-reporter/blob/master/OWNERS

others are to be updated

**Comment by harshad16** [comment]
Closing this issue as we already adjusted the required repos 
and going forwards, we would require a team meeting for this.
Thanks all for the work.
