### ISSUE TITLE
Use github project beta for planning

### ISSUE THREAD

**Issue by harshad16** [thoth-station/core#424]
## Problem statement
During the retro, it was suggested to use the GitHub project board of type beta for sprint planning.

## Acceptance Criteria

- [ ] example

**Comment by harshad16** [comment]
cc: @Gkrumbach07 @codificat

**Comment by codificat** [comment]
Some work in progress in testing this: https://github.com/orgs/thoth-station/projects/49

**Comment by codificat** [comment]
/assign

Discussed in today's tech talk session: the proposal is to unify all the SIG and WG work into one single board, https://github.com/orgs/thoth-station/projects/49

/triage accepted
/lifecycle active

**Comment by codificat** [comment]
This is now done: the new unified [planning board](https://github.com/orgs/thoth-station/projects/49/views/1) contains all the issues from all the SIG and WG boards, and views that show the content split by SIG/WG.

/close
