### ISSUE TITLE
Introduce Bitwarden secret management for the team thoth

### ISSUE THREAD

**Issue by harshad16** [thoth-station/core#426]
## Problem statement
We were using the gopass in past for secret management and pass around in team. Lately, we have been relying on the secret encrypted in thoth-application or directly access them from openshift clusters. However, it would be great to have Bit warden which supports in Redhat and can be used for our team.

## Proposal description
we need an orgnization in bit warden for sharing secret between team.
As conveniently the organization can be bound by LDAP group.

Reference:
- https://source.redhat.com/departments/it/it-information-security/wiki/intro_to_bitwarden_password_management_and_frequently_asked_questions
- https://vault.bitwarden.com/#/login

**Comment by goern** [comment]
can we use ksops to achieve the same goal? would that be a little bit more open?

**Comment by harshad16** [comment]
We can there are few details, which are not really required to be open.
Most of the team in RedHat has started to use this. 

we would contiinue to use ksops for the bits, that can be open for collaborators.

**Comment by goern** [comment]
I think this is fine, right?

**Comment by harshad16** [comment]
yes , thank you for the setup.
