### ISSUE TITLE
Provide sig chairs write access

### ISSUE THREAD

**Issue by harshad16** [thoth-station/core#427]
## Problem statement
As we are having grooming and planning meetings in sigs.
It would make the life of sig chairs easier if they had to write access in the repos.

**Comment by goern** [comment]
I manually configured each project to have admin access for the ...-leads team. let me know if this does the trick, if not, feel free to re-open this issue

/close

**Comment by goern** [comment]
is this done?

**Comment by codificat** [comment]
> is this done?

In theory yes, via #438.

FWIW, from my side I see that I now have write access to (most?) repos - which I did not before.

The new group created on that PR (members, repos, ...) is https://github.com/orgs/thoth-station/teams/sigchairs

LGTM
