### ISSUE TITLE
[5pt] Create a new Github App for TTM service

### ISSUE THREAD

**Issue by Gkrumbach07** [thoth-station/core#433]
## Problem statement

As a user of the TTM model, I want to be able to add the TTM model capabilities to my GitHub workflow.

## High-level Goals

- Create a new repo for the Github App
- Create the app based on the service's [overview](https://github.com/thoth-station/core/issues/432)
- 
## Proposal description

The Github App should be an MVP of the TTM service. It does not need to support generating custom trained models yet.

The MVP should include:
- inputs for model endpoint url
- commenting output of TTM model (mapped to real text)
    - include top 3 predictions with confidence level

### Alternatives

See https://github.com/thoth-station/core/issues/432 for alternatives

## Acceptance Criteria

- [x] New repo
- [x] Github App can be added to a workflow and runs correctly

**Comment by goern** [comment]
@Gkrumbach07 is this service available on the github marketplace?
