### ISSUE TITLE
Gather user feedback/opinions on useful Scorecard metrics

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/core#442]
This issue is part of the following **EPIC**: https://github.com/thoth-station/core/issues/434

_**4. Implement the global scoring logic**_

_For example, if a software stack is in the 95th percentile of packages with the best development practices (CI/CD, testing...), score it as "A" for this category. Compute a global score from the different category scores._

 _**Gather user feedback/opinions on what metrics would be the most relevant to them**_

Next steps:

- [ ] Discuss with current users of Thoth (i.e. Packit team) about what Scorecard metrics would be the most useful for them to see

**Comment by Gkrumbach07** [comment]
/triage accepted

create a google form and send it to teams that use Thoth and aggregate results. Scorecards also give importance information for each metric they provide.

**Comment by goern** [comment]
let's assume that some scorecard metrics are more useful than others, see https://github.com/ossf/scorecard/blob/main/docs/checks.md so we include

- prevent Trojan: Binary-Artifacts
- prevent Trojan: Branch-Protection
- keep quality: CI-Tests
- keep quality: CII-Best-Practices
- keep quality: Code-Review
- keep quality: Pinned-Dependencies
- maintained code: Contributors
- maintained code: Dependency-Update-Tool
- maintained code: Maintained
