### ISSUE TITLE
would like to have a label `blocked` for marking issues blocked.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/core#469]
## Problem statement
I would like to have a label `blocked` for marking issues blocked.
As it makes it clear on the issue. 

## High-level Goals
 - Include blocked label.

## Proposal description

- Include the label 
 https://github.com/thoth-station/core/blob/main/community/labels.yaml
 and update the description: https://github.com/thoth-station/core/blob/main/community/labels.md

## Acceptance Criteria
- [ ] Include label via core https://github.com/thoth-station/core/blob/main/community/labels.md

**Comment by goern** [comment]
sounds good to me. what do we do with blocked issues and pull requests? or is that just an informational label?

**Comment by harshad16** [comment]
It is an informational label to communicate with contributor that work is in progress though blocked with some reason.

> what do we do with blocked issues and pull requests?

- we would try to unblock them based on priority or address them more in sig meetings.

**Comment by VannTen** [comment]
Should that be a standalone labels, or part of `lifecycle/*` ? (`lifecycle/active` )
Or another one ?

**Comment by harshad16** [comment]
Great question.
Any place would work. 

As lifecycle labels are from Kubernetes, we can check if the blocked label is already present.

**Comment by goern** [comment]
Kubernetes does not have these semantics, they have issue that blocks releases, but they don't indicate that an issue is blocked... https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml

putting it in the lifecycle context makes sense...

**Comment by VannTen** [comment]
Applying lifecycle labels is done by prow though ? We should check if we can add our own stuff somewhere in prow config.

**Comment by goern** [comment]
adding at to https://github.com/operate-first/apps/blob/master/prow/overlays/smaug/plugins.yaml#L6 should at least enable us to do `/label lifecycle/blocked`, I'm unsure about `/lifecycle blocked`

**Comment by codificat** [comment]
reviewing this today, we agreed that the status available via the project board is enough for the time being
/close
