### ISSUE TITLE
label_sync post-submit job fails to complete

### ISSUE THREAD

**Issue by codificat** [thoth-station/core#474]
## Bug description

The last execution of the `thoth-station-labels` prow [postsubmit job](https://github.com/thoth-station/core/blob/59b769b858e5fc76bb9ab91755dce177cf5ea4c8/.prow.yaml#L114) failed to complete its work after running for 2 hours.

It seems that the timeout for that job is 2 hours but it takes longer to complete the `label_sync` exectution.

### Steps to Reproduce
1. Go to #472 
2. Look at the proposed label changes
3. Check a few repositories
4. See that some repos were fully updated but others were not

### Actual behavior

Example: currently this is the list of `wg/*` labels [for the core repo](https://github.com/thoth-station/core/labels?q=wg) (it was properly updated):

![imatge](https://user-images.githubusercontent.com/709574/203044075-17c11d2f-e15b-4817-9b8b-a10f6cee1eef.png)

and this is the same list [for the meteor-operator repo](https://github.com/thoth-station/meteor-operator/labels?q=wg):

![imatge](https://user-images.githubusercontent.com/709574/203044262-04bede3e-8ff5-4fab-ac2f-22906db52e68.png)

### Expected behavior

Labels updated on all repos. `label_sync` complete.

### Additional context

I managed to download the log output of the job. It's too long to attach here I'm afraid. A couple of highlights:

- start time: 2022-11-18T11:03:20Z
- end time: 2022-11-18T13:03:35Z

Last few log entries:

```json
{
  "component": "entrypoint",
  "file": "k8s.io/test-infra/prow/entrypoint/run.go:165",
  "func": "k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess",
  "level": "error",
  "msg": "Process did not finish before 2h0m0s timeout",
  "severity": "error",
  "time": "2022-11-18T13:03:20Z"
}
{
  "client": "github",
  "component": "label_sync",
  "file": "k8s.io/test-infra/prow/github/client.go:917",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "UpdateRepoLabel(thoth-station, pipeline-helpers, wg/cnbi, wg/cre, 0052cc)",
  "severity": "info",
  "time": "2022-11-18T13:03:21Z"
}
{
  "client": "github",
  "component": "label_sync",
  "file": "k8s.io/test-infra/prow/github/client.go:917",
  "func": "k8s.io/test-infra/prow/github.(*client).log",
  "level": "info",
  "msg": "AddLabels(thoth-station, meteor-operator, 123, [wg/cre])",
  "severity": "info",
  "time": "2022-11-18T13:03:33Z"
}
{
  "component": "entrypoint",
  "file": "k8s.io/test-infra/prow/entrypoint/run.go:255",
  "func": "k8s.io/test-infra/prow/entrypoint.gracefullyTerminate",
  "level": "error",
  "msg": "Process did not exit before 15s grace period",
  "severity": "error",
  "time": "2022-11-18T13:03:35Z"
}
{
  "component": "entrypoint",
  "error": "process timed out",
  "file": "k8s.io/test-infra/prow/entrypoint/run.go:80",
  "func": "k8s.io/test-infra/prow/entrypoint.Options.Run",
  "level": "error",
  "msg": "Error executing test process",
  "severity": "error",
  "time": "2022-11-18T13:03:35Z"
}
```

**Comment by codificat** [comment]
/sig devsecops
/priority important-longterm

and I believe it's clear enough to say
/triage accepted

**Comment by goern** [comment]
for https://github.com/thoth-station/core/compare/07f42b66fcb1...f8ff9eb1b150 it executed successfully, please recheck.

/priority awaiting-more-evidence
/remove-priority important-longterm

**Comment by codificat** [comment]
> for [07f42b6...f8ff9eb](https://github.com/thoth-station/core/compare/07f42b66fcb1...f8ff9eb1b150) it executed successfully, please recheck.

logs are gone by now... but taking a quick look at a few repos, labels seem to be in sync now AFAICT, so
/close
