### ISSUE TITLE
introduce THOTH_SOLVER_DEBUG

### ISSUE THREAD

**Issue by goern** [thoth-station/core#54]
put THOTH_SOLVER_DEBUG into a configmap, add it to ansible playbooks so that we can use it at https://github.com/thoth-station/graph-refresh-job/blob/master/app.py#L114

Add/check
- [ ] configmap template
- [ ] ansible playbooks and roles
- [ ] deployment config and cronjobs

**Comment by fridex** [comment]
Let's follow the pre-configured common logging schema across services - it will simplify things later on - the variable name should be named ```THOTH_LOG_SOLVER``` as described in https://thoth-station.github.io/docs/thoth.common.html#module-thoth.common.logging
